# Generated by Django 3.2.13 on 2022-06-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('recipes', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countofingredient',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='ingredients.CountOfIngredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='tags.Tag', verbose_name='Теги'),
        ),
        migrations.DeleteModel(
            name='CountOfIngredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
