# Generated by Django 3.2.13 on 2022-06-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
